# Generated by Django 3.1.4 on 2021-02-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logo',
            old_name='logo',
            new_name='pictures',
        ),
    ]
